#!/bin/bash
for y in $(for z in `nginx -qT|grep 'ssl_certificate\ '|egrep -Ev "^#|^nginx\:"|sed "s#.*\/##g;s/\.pem\;//g"`;do /root/CertLE/date_checker $z 2>/dev/null|grep ALERT;done|awk '{print $1}');do
  home_domain=$(nginx -T|grep $y|grep 'ssl_certificate '|sed "s#^.*\/home\/##g; s/\.pem\;//g")
  useris=`echo $home_domain|cut -d/ -f1`
  domainis=`echo $home_domain|cut -d/ -f2`

  homeis2=`nginx -T|grep -A3 server_name|grep $domainis -A3|grep 'root '|awk '{print $2}'|sed "s/;//g"`
  if [[ -n `echo $domainis|grep "^dev\."` ]];then
    homeis="/home/$useris/dev/"
  else
    homeis=/home/$useris
  fi

  echo ::: home $homeis or $homeis2, domain: $domainis, user: $useris
  /root/CertLE/doit $domainis $useris $homeis
  /root/CertLE/doit $domainis $useris $homeis2
done

if `nginx -qt`;then
  nginx -s reload
fi
