#!/bin/bash
if [[ $2 == "" ]];then
  echo Help:
  echo $0 domain.com username \[webroot\]
else
  cd=`pwd`
  if [[ $3 != "" ]];then
    wr=$3
  else
    wr="/home/$2/www/"
  fi
  cd /root/CertLE
  workdir="certs/$2/`date +'%F_%H%M%S'`"
  mkdir -p $workdir
  firstdomain=`echo $1|cut -d, -f1`
  san=`echo $1|sed "s/,/ -d /g"`
  ./certle genrsa 4096 > $workdir/$firstdomain.key && \
    ./certle cert /root/LEaccount.key $workdir/$firstdomain.key -w $wr -d $san --cert $workdir/$firstdomain.crt --chain $workdir/$firstdomain.ca --fullchain $workdir/$firstdomain.pem --csr $workdir/$firstdomain.csr
  if [ $? == "0" ];then
    echo :::: done issuing SSL
    if [[ "`openssl x509 -noout -modulus -in $workdir/$firstdomain.crt| openssl md5|awk '{print $2}'`" == "`openssl rsa -noout -modulus -in $workdir/$firstdomain.key| openssl md5|awk '{print $2}'`" ]];then
      echo md5 matches
      cp -p $workdir/* /home/$2/
      if `nginx -qt`;then
        nginx -s reload
      fi
    else
      echo md5 did not match, so not updating /home/$2/ , please check /root/CertLE/$workdir/
    fi
  fi
  #cp -p $1.key /home/$2/
  cd `cd`
fi
