#!/bin/bash
if ! certbot --version 2>/dev/null;then echo -e "\n::: certbot missing\n";apt install certbot;fi

if [[ $2 == "" ]];then
  echo :: Usage: $0 domain.com username \[webroot\] \[nginx\]
else
  cd=`pwd`
  firstdomain=`echo $1|cut -d, -f1`
  if [[ $3 != "" ]];then
    wr=$3
  elif [[ -d "/home/$2/websites/$firstdomain/www" ]];then
    wr="/home/$2/websites/$firstdomain/www"
  elif [[ -d "/home/$2/www" ]];then
    wr="/home/$2/www/"
  else
    wr=""
  fi
  san=`echo $1|sed "s/,/ -d /g"`
  if [[ $4 == "nginx" ]];then
    webroot_args="--nginx"
  elif [[ $wr != "" ]];then
    webroot_args="--webroot -w $wr"
  else
    webroot_args="--nginx"
  fi
  certbot certonly --agree-tos --expand -d $1 --cert-path /home/$2/$firstdomain.crt --fullchain-path /home/$2/$firstdomain.pem --chain-path /home/$2/$firstdomain.crt.ca $webroot_args --email ron@xron.net --cert-name $firstdomain --reinstall --rsa-key-size 4096 -nq
  if [ $? == "0" ];then
    echo :: done issuing SSL
    if [[ "`openssl x509 -noout -modulus -in /etc/letsencrypt/live/$firstdomain/cert.pem| openssl md5|awk '{print $2}'`" == "`openssl rsa -noout -modulus -in /etc/letsencrypt/live/$firstdomain/privkey.pem| openssl md5|awk '{print $2}'`" ]];then
      echo md5 matches
      ln -s /etc/letsencrypt/live/$firstdomain/cert.pem /home/$2/$firstdomain.crt
      ln -s /etc/letsencrypt/live/$firstdomain/chain.pem /home/$2/$firstdomain.ca
      ln -s /etc/letsencrypt/live/$firstdomain/fullchain.pem /home/$2/$firstdomain.pem
      ln -s /etc/letsencrypt/live/$firstdomain/privkey.pem /home/$2/$firstdomain.key
      if `nginx -qt`;then
        nginx -s reload
      fi
    else
      echo md5 did not match, so not updating /home/$2/ , please check /etc/letsencrypt/live/$firstdomain/
    fi
  fi
  #cp -p $1.key /home/$2/
  cd `cd`
fi
